cat pkm_banjarbaru_utara_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(5\,/g -e s/$/\)\;/g > pkm_banjarbaru_utara_umum_insert.sql
cat pkm_banjarbaru_utara_blud.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(6\,/g -e s/$/\)\;/g > pkm_banjarbaru_utara_blud_insert.sql
cat pkm_banjarbaru_selatan_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(7\,/g -e s/$/\)\;/g > pkm_banjarbaru_selatan_umum_insert.sql
cat pkm_banjarbaru_selatan_blud.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(8\,/g -e s/$/\)\;/g > pkm_banjarbaru_selatan_blud_insert.sql
cat pkm_sungai_besar_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(820\,/g -e s/$/\)\;/g > pkm_sungai_besar_umum_insert.sql
cat pkm_sungai_besar_blud.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(814\,/g -e s/$/\)\;/g > pkm_sungai_besar_blud_insert.sql
cat pkm_landasan_ulin_timur_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(829\,/g -e s/$/\)\;/g > pkm_landasan_ulin_timur_umum_insert.sql
cat pkm_landasan_ulin_timur_hibah_pihak_ketiga_covid.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(830\,/g -e s/$/\)\;/g > pkm_landasan_ulin_timur_hibah_pihak_ketiga_covid_insert.sql
cat pkm_rawat_inap_cempaka_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(832\,/g -e s/$/\)\;/g > pkm_rawat_inap_cempaka_umum_insert.sql
cat pkm_rawat_inap_cempaka_blud.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(836\,/g -e s/$/\)\;/g > pkm_rawat_inap_cempaka_blud_insert.sql
cat pkm_guntung_payung_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(845\,/g -e s/$/\)\;/g > pkm_guntung_payung_umum_insert.sql
cat pkm_landasan_ulin_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(859\,/g -e s/$/\)\;/g > pkm_landasan_ulin_umum_insert.sql
cat pkm_liang_anggang_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(860\,/g -e s/$/\)\;/g > pkm_liang_anggang_umum_insert.sql
cat pkm_sungai_ulin_umum.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(862\,/g -e s/$/\)\;/g > pkm_sungai_ulin_umum_insert.sql
cat pkm_sungai_ulin_blud.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(863\,/g -e s/$/\)\;/g > pkm_sungai_ulin_blud_insert.sql
cat pkm_sungai_ulin_hibah_pihak_ketiga_covid.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(864\,/g -e s/$/\)\;/g > pkm_sungai_ulin_hibah_pihak_ketiga_covid_insert.sql
cat rsud_skpd_btt.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(1\,/g -e s/$/\)\;/g > rsud_skpd_btt_insert.sql
cat rsud_skpd_btt.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(1\,/g -e s/$/\)\;/g > rsud_skpd_btt_insert.sql
cat rsud_skpd_btt.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(1\,/g -e s/$/\)\;/g > rsud_skpd_btt_insert.sql
cat rsud_skpd_btt.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(1\,/g -e s/$/\)\;/g > rsud_skpd_btt_insert.sql
cat rsud_skpd_btt.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(1\,/g -e s/$/\)\;/g > rsud_skpd_btt_insert.sql
cat rsud_skpd_btt.sql | sed -e s/^/INSERT\ INTO\ persediaan\ \(id_transaksi\,\ id_barang\,\ jumlah\,\ harga\)\ VALUES\ \(1\,/g -e s/$/\)\;/g > rsud_skpd_btt_insert.sql
