#cat tebingtinggi/admin.py  | sed -e  s/TebingTinggi/Setwan/g  | sed -e s/tebingtinggi/setwan/g  | sed -e  s/38/1/g > setwan/admin.py

#sekolah sebagai SKPD
#buat admin untuk SKPD
# baris pertama > baris selanjutnya >>

cat admin_tt.py | sed -e s/TebingTinggi/DINAS_PENDIDIKAN/g | sed -e s/38/1/g > admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_SGR_KEG_BELAJAR/g | sed -e s/38/2/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_DISDIK_WIL_I/g | sed -e s/38/3/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_DISDIK_WIL_II/g | sed -e s/38/4/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_KESEHATAN/g | sed -e s/38/5/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_BANJARBARU_UTARA/g | sed -e s/38/6/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_BANJARBARU_SELATAN/g | sed -e s/38/7/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_SUNGAI_BESAR/g | sed -e s/38/8/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_RAWAT_INAP_CEMPAKA/g | sed -e s/38/9/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_GUNTUNG_PAYUNG/g | sed -e s/38/10/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_LANDASAN_ULIN/g | sed -e s/38/11/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_LIANG_ANGGANG/g | sed -e s/38/12/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_SUNGAI_ULIN/g | sed -e s/38/13/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_GUDANG_OBAT/g | sed -e s/38/14/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_GUNTUNG_MANGGIS/g | sed -e s/38/15/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/RSD_IDAMAN_SKPD/g | sed -e s/38/16/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/RSD_IDAMAN_BLUD/g | sed -e s/38/17/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DPUPR/g | sed -e s/38/18/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_PERKIM/g | sed -e s/38/19/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/SATPOLPP/g | sed -e s/38/20/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BADAN_KESBANGPOL/g | sed -e s/38/21/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_SOSIAL/g | sed -e s/38/22/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BPBD/g | sed -e s/38/23/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_KPPP/g | sed -e s/38/24/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_LINGKUNGAN_HIDUP/g | sed -e s/38/26/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_LABORATORIUM_L_H/g | sed -e s/38/27/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_DUKCATPIL/g | sed -e s/38/28/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DPPKBPMPPA/g | sed -e s/38/29/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_PERHUBUNGAN/g | sed -e s/38/30/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPT_PENGUJIAN_KEND_BERM/g | sed -e s/38/31/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPT_PERPARKIRAN/g | sed -e s/38/32/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_KOMINFO/g | sed -e s/38/33/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_KUKMTK/g | sed -e s/38/34/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DPMPTSP/g | sed -e s/38/35/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_POKP/g | sed -e s/38/36/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_ARSIP_DAN_PERPUST/g | sed -e s/38/37/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DINAS_PERDAGANGAN/g | sed -e s/38/38/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_PASAR_BAUNTUNG/g | sed -e s/38/39/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_PASAR_ULIN_RAYA/g | sed -e s/38/40/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_GUDANG_TRANSITO/g | sed -e s/38/41/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPTD_METROLOGI/g | sed -e s/38/42/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/DPRD/g | sed -e s/38/43/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEPALA_DAERAH_DAN_WAKIL/g | sed -e s/38/44/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/SEKRETARIAT_DAERAH/g | sed -e s/38/45/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/SEKRETARIAT_DPRD/g | sed -e s/38/46/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEC_BANJARBARU_SELATAN/g | sed -e s/38/47/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LOKTABAT_SELATAN/g | sed -e s/38/48/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_KEMUNING/g | sed -e s/38/49/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_GUNTUNG_PAIKAT/g | sed -e s/38/50/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_SUNGAI_BESAR/g | sed -e s/38/51/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEC_BANJARBARU_UTARA/g | sed -e s/38/52/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LOKTABAT_UTARA/g | sed -e s/38/53/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_KOMET/g | sed -e s/38/54/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_MENTAOS/g | sed -e s/38/55/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_SUNGAI_ULIN/g | sed -e s/38/56/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEC_CEMPAKA/g | sed -e s/38/57/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_CEMPAKA/g | sed -e s/38/58/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_PALAM/g | sed -e s/38/59/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_BANGKAL/g | sed -e s/38/60/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_SUNGAI_TIUNG/g | sed -e s/38/61/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEC_LANDASAN_ULIN/g | sed -e s/38/62/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LANDASAN_ULIN_TIMUR/g | sed -e s/38/63/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_GUNTUNG_PAYUNG/g | sed -e s/38/64/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_SYAMSUDIN_NOOR/g | sed -e s/38/65/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_GUNTUNG_MANGGIS/g | sed -e s/38/66/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEC_LIANG_ANGGANG/g | sed -e s/38/67/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LANDASAN_ULIN_TENGAH/g | sed -e s/38/68/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LANDASAN_ULIN_UTARA/g | sed -e s/38/69/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LANDASAN_ULIN_BARAT/g | sed -e s/38/70/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/KEL_LANDASAN_ULIN_SELATAN/g | sed -e s/38/71/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPT_PEMB_TERNAK_PUSKEWAN/g | sed -e s/38/72/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/INSPEKTORAT/g | sed -e s/38/73/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BADAN_PP_LITBANG_DA/g | sed -e s/38/74/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BPKAD_SKPD/g | sed -e s/38/75/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BPKAD_PPKD/g | sed -e s/38/76/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BADAN_P_PAJAK_RETRIBUSI/g | sed -e s/38/77/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPT_PAJAK_DAERAH_WILAYAH_I/g | sed -e s/38/78/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/UPT_PAJAK_DAERAH_WILAYAH_II/g | sed -e s/38/79/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/BKPPD/g | sed -e s/38/80/g >> admin_gabungan
cat admin_tt.py | sed -e s/TebingTinggi/PKM_LANDASAN_ULIN_TIMUR/g | sed -e s/38/175/g >> admin_gabungan
