#!/bin/sh
#muhammad@muntaza.id
#copy file ke folder lain

#cat 01_setwan/daftar_pengadaan_skpd_p.xml | sed -e s/setwan/setda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g >  02_setda/daftar_pengadaan_skpd_p.xml

#dinas_pendidikan,1,01_dinas_pendidikan

#cat 01_dinas_pendidikan/buku_beban_skpd.xml | sed -e s/dinas_pendidikan/uptd_sgr_keg_belajar/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g > 02_uptd_sgr_keg_belajar/buku_beban_skpd.xml

cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>82/g > 082_sdn_1_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>83/g > 083_sdn_1_guntung_manggis/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_guntung_paikat/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>84/g > 084_sdn_1_guntung_paikat/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_guntung_payung/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>85/g > 085_sdn_1_guntung_payung/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_kemuning/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>86/g > 086_sdn_1_kemuning/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_komet/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>87/g > 087_sdn_1_komet/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_landasan_ulin_barat/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>88/g > 088_sdn_1_landasan_ulin_barat/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_landasan_ulin_selatan/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>89/g > 089_sdn_1_landasan_ulin_selatan/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_landasan_ulin_tengah/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>90/g > 090_sdn_1_landasan_ulin_tengah/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_landasan_ulin_timur/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>91/g > 091_sdn_1_landasan_ulin_timur/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_landasan_ulin_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>92/g > 092_sdn_1_landasan_ulin_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_loktabat_selatan/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>93/g > 093_sdn_1_loktabat_selatan/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_loktabat_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>94/g > 094_sdn_1_loktabat_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_mentaos/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>95/g > 095_sdn_1_mentaos/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_palam/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>96/g > 096_sdn_1_palam/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_sungai_besar/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>97/g > 097_sdn_1_sungai_besar/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_sungai_tiung/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>98/g > 098_sdn_1_sungai_tiung/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>99/g > 099_sdn_1_sungai_ulin/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_1_syamsudin_noor/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>100/g > 100_sdn_1_syamsudin_noor/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_bangkal/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>101/g > 101_sdn_2_bangkal/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>102/g > 102_sdn_2_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>103/g > 103_sdn_2_guntung_manggis/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_guntung_paikat/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>104/g > 104_sdn_2_guntung_paikat/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_guntung_payung/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>105/g > 105_sdn_2_guntung_payung/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_kemuning/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>106/g > 106_sdn_2_kemuning/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_komet/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>107/g > 107_sdn_2_komet/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_landasan_ulin_barat/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>108/g > 108_sdn_2_landasan_ulin_barat/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_landasan_ulin_timur/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>109/g > 109_sdn_2_landasan_ulin_timur/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_landasan_ulin_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>110/g > 110_sdn_2_landasan_ulin_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_loktabat_selatan/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>111/g > 111_sdn_2_loktabat_selatan/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_loktabat_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>112/g > 112_sdn_2_loktabat_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_mentaos/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>113/g > 113_sdn_2_mentaos/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_palam/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>114/g > 114_sdn_2_palam/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_sungai_besar/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>115/g > 115_sdn_2_sungai_besar/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_sungai_tiung/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>116/g > 116_sdn_2_sungai_tiung/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>117/g > 117_sdn_2_sungai_ulin/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_2_syamsudin_noor/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>118/g > 118_sdn_2_syamsudin_noor/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_bangkal/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>119/g > 119_sdn_3_bangkal/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>120/g > 120_sdn_3_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>121/g > 121_sdn_3_guntung_manggis/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_guntung_payung/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>122/g > 122_sdn_3_guntung_payung/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_kemuning/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>123/g > 123_sdn_3_kemuning/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_komet/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>124/g > 124_sdn_3_komet/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_landasan_ulin_timur/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>125/g > 125_sdn_3_landasan_ulin_timur/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_loktabat_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>126/g > 126_sdn_3_loktabat_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_palam/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>127/g > 127_sdn_3_palam/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_sungai_besar/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>128/g > 128_sdn_3_sungai_besar/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_sungai_tiung/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>129/g > 129_sdn_3_sungai_tiung/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>130/g > 130_sdn_3_sungai_ulin/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_3_syamsudin_noor/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>131/g > 131_sdn_3_syamsudin_noor/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>132/g > 132_sdn_4_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>133/g > 133_sdn_4_guntung_manggis/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_komet/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>134/g > 134_sdn_4_komet/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_loktabat_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>135/g > 135_sdn_4_loktabat_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_sungai_besar/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>136/g > 136_sdn_4_sungai_besar/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>137/g > 137_sdn_4_sungai_ulin/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_4_syamsudin_noor/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>138/g > 138_sdn_4_syamsudin_noor/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>139/g > 139_sdn_5_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>140/g > 140_sdn_5_guntung_manggis/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_komet/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>141/g > 141_sdn_5_komet/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_loktabat_utara/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>142/g > 142_sdn_5_loktabat_utara/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_sungai_besar/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>143/g > 143_sdn_5_sungai_besar/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>144/g > 144_sdn_5_sungai_ulin/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_5_syamsudin_noor/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>145/g > 145_sdn_5_syamsudin_noor/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/sdn_6_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>146/g > 146_sdn_6_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_1/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>147/g > 147_smp_negeri_1/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_2/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>148/g > 148_smp_negeri_2/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_3/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>149/g > 149_smp_negeri_3/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_4/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>150/g > 150_smp_negeri_4/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_5/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>151/g > 151_smp_negeri_5/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_6/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>152/g > 152_smp_negeri_6/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_8/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>153/g > 153_smp_negeri_8/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_9/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>154/g > 154_smp_negeri_9/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_10/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>155/g > 155_smp_negeri_10/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_11/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>156/g > 156_smp_negeri_11/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_12/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>157/g > 157_smp_negeri_12/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_13/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>158/g > 158_smp_negeri_13/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_14/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>159/g > 159_smp_negeri_14/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/smp_negeri_15/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>160/g > 160_smp_negeri_15/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/tk_negeri_idaman/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>161/g > 161_tk_negeri_idaman/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/tk_negeri_pembina_cempaka/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>162/g > 162_tk_negeri_pembina_cempaka/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/tk_negeri_pembina_kota/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>163/g > 163_tk_negeri_pembina_kota/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/tk_negeri_pembina_l_ulin/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>164/g > 164_tk_negeri_pembina_l_ulin/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/tk_negeri_pembina_l_anggang/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>165/g > 165_tk_negeri_pembina_l_anggang/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_pemerintahan/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>166/g > 166_bag_pemerintahan/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_kerjasama_dan_agraria/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>167/g > 167_bag_kerjasama_dan_agraria/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_hukum/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>168/g > 168_bag_hukum/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_ekobang/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>169/g > 169_bag_ekobang/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_pbj/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>170/g > 170_bag_pbj/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_kesra/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>171/g > 171_bag_kesra/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_umum/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>172/g > 172_bag_umum/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_humas_dan_protokol/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>173/g > 173_bag_humas_dan_protokol/daftar_persediaan_skpd.xml
cat 081_sdn_1_bangkal/daftar_persediaan_skpd.xml | sed -e s/sdn_1_bangkal/bag_organisasi/g | sed -e s/\<CriteriaDefaults\>81/\<CriteriaDefaults\>174/g > 174_bag_organisasi/daftar_persediaan_skpd.xml
