#!/bin/sh
#muhammad@muntaza.id
#copy file ke folder lain

#cat 01_setwan/daftar_pengadaan_skpd_p.xml | sed -e s/setwan/setda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g >  02_setda/daftar_pengadaan_skpd_p.xml


#dinas_pendidikan,1,01_dinas_pendidikan


cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_sgr_keg_belajar/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g > 02_uptd_sgr_keg_belajar/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_disdik_wil_i/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>3/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 03_uptd_disdik_wil_i/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_disdik_wil_ii/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>4/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 04_uptd_disdik_wil_ii/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_kesehatan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>5/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 05_dinas_kesehatan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_banjarbaru_utara/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>6/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 06_pkm_banjarbaru_utara/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_banjarbaru_selatan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>7/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 07_pkm_banjarbaru_selatan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_sungai_besar/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>8/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 08_pkm_sungai_besar/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_rawat_inap_cempaka/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>9/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 09_pkm_rawat_inap_cempaka/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_guntung_payung/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>10/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 10_pkm_guntung_payung/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_landasan_ulin/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>11/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 11_pkm_landasan_ulin/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_liang_anggang/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>12/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 12_pkm_liang_anggang/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>13/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 13_pkm_sungai_ulin/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_gudang_obat/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>14/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 14_uptd_gudang_obat/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>15/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 15_pkm_guntung_manggis/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/rsd_idaman_skpd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>16/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 16_rsd_idaman_skpd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/rsd_idaman_blud/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>17/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 17_rsd_idaman_blud/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dpupr/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>18/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 18_dpupr/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_perkim/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>19/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 19_dinas_perkim/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/satpolpp/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>20/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 20_satpolpp/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/badan_kesbangpol/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>21/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 21_badan_kesbangpol/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_sosial/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>22/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 22_dinas_sosial/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/bpbd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>23/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 23_bpbd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_kppp/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>24/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 24_dinas_kppp/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_lingkungan_hidup/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>26/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 26_dinas_lingkungan_hidup/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_laboratorium_l_h/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>27/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 27_uptd_laboratorium_l_h/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_dukcatpil/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>28/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 28_dinas_dukcatpil/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dppkbpmppa/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>29/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 29_dppkbpmppa/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_perhubungan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>30/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 30_dinas_perhubungan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/upt_pengujian_kend_berm/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>31/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 31_upt_pengujian_kend_berm/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/upt_perparkiran/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>32/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 32_upt_perparkiran/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_kominfo/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>33/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 33_dinas_kominfo/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_kukmtk/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>34/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 34_dinas_kukmtk/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dpmptsp/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>35/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 35_dpmptsp/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_pokp/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>36/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 36_dinas_pokp/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_arsip_dan_perpust/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>37/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 37_dinas_arsip_dan_perpust/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dinas_perdagangan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>38/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 38_dinas_perdagangan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_pasar_bauntung/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>39/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 39_uptd_pasar_bauntung/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_pasar_ulin_raya/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>40/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 40_uptd_pasar_ulin_raya/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_gudang_transito/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>41/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 41_uptd_gudang_transito/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/uptd_metrologi/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>42/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 42_uptd_metrologi/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/dprd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>43/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 43_dprd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kepala_daerah_dan_wakil/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>44/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 44_kepala_daerah_dan_wakil/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/sekretariat_daerah/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>45/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 45_sekretariat_daerah/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/sekretariat_dprd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>46/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 46_sekretariat_dprd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kec_banjarbaru_selatan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>47/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 47_kec_banjarbaru_selatan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_loktabat_selatan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>48/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 48_kel_loktabat_selatan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_kemuning/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>49/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 49_kel_kemuning/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_guntung_paikat/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>50/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 50_kel_guntung_paikat/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_sungai_besar/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>51/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 51_kel_sungai_besar/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kec_banjarbaru_utara/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>52/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 52_kec_banjarbaru_utara/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_loktabat_utara/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>53/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 53_kel_loktabat_utara/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_komet/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>54/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 54_kel_komet/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_mentaos/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>55/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 55_kel_mentaos/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_sungai_ulin/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>56/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 56_kel_sungai_ulin/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kec_cempaka/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>57/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 57_kec_cempaka/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_cempaka/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>58/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 58_kel_cempaka/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_palam/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>59/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 59_kel_palam/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_bangkal/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>60/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 60_kel_bangkal/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_sungai_tiung/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>61/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 61_kel_sungai_tiung/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kec_landasan_ulin/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>62/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 62_kec_landasan_ulin/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_landasan_ulin_timur/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>63/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 63_kel_landasan_ulin_timur/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_guntung_payung/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>64/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 64_kel_guntung_payung/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_syamsudin_noor/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>65/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 65_kel_syamsudin_noor/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_guntung_manggis/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>66/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 66_kel_guntung_manggis/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kec_liang_anggang/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>67/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 67_kec_liang_anggang/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_landasan_ulin_tengah/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>68/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 68_kel_landasan_ulin_tengah/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_landasan_ulin_utara/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>69/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 69_kel_landasan_ulin_utara/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_landasan_ulin_barat/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>70/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 70_kel_landasan_ulin_barat/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/kel_landasan_ulin_selatan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>71/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 71_kel_landasan_ulin_selatan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/upt_pemb_ternak_puskewan/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>72/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 72_upt_pemb_ternak_puskewan/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/inspektorat/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>73/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 73_inspektorat/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/badan_pp_litbang_da/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>74/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 74_badan_pp_litbang_da/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/bpkad_skpd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>75/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 75_bpkad_skpd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/bpkad_ppkd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>76/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 76_bpkad_ppkd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/badan_p_pajak_retribusi/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>77/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 77_badan_p_pajak_retribusi/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/upt_pajak_daerah_wilayah_i/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>78/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 78_upt_pajak_daerah_wilayah_i/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/upt_pajak_daerah_wilayah_ii/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>79/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 79_upt_pajak_daerah_wilayah_ii/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/bkppd/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>80/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 80_bkppd/rekap_kartu_barang_skpd.xml
cat 01_dinas_pendidikan/rekap_kartu_barang_skpd.xml | sed -e s/dinas_pendidikan/pkm_landasan_ulin_timur/g | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>175/g | sed -e s/\<CriteriaDefaults\>3/\<CriteriaDefaults\>1/g  > 175_pkm_landasan_ulin_timur/rekap_kartu_barang_skpd.xml
